"""Update schemas + models

Revision ID: 5134164e8c5d
Revises: c97452152de5
Create Date: 2025-10-19 17:21:27.203200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5134164e8c5d'
down_revision: Union[str, Sequence[str], None] = 'c97452152de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_profile', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('provider', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('provider', 'public_contact',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('provider', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('provider_user_id_key'), 'provider', type_='unique')
    op.drop_column('provider', 'id')
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('user', 'provider', 'admin', name='user_role'),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('user', 'provider', 'admin', name='user_role'),
               nullable=True)
    op.add_column('provider', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('provider_user_id_key'), 'provider', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('provider', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider', 'public_contact',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('provider', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('organization_profile', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
