"""Update models

Revision ID: a44aa0f07df1
Revises: 54af553a9765
Create Date: 2025-10-28 20:18:39.836861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a44aa0f07df1'
down_revision: Union[str, Sequence[str], None] = '54af553a9765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=False),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('public_contact', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('organization_profile')
    op.drop_table('provider')
    op.drop_table('individual_profile')
    op.add_column('user', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.execute("""
        UPDATE "user"
        SET nickname = split_part(email, '@', 1)
        WHERE email LIKE '%@%'
    """)
    
    op.execute("""
        UPDATE "user"
        SET nickname = 'user_' || substr(md5(id::text), 1, 8)
        WHERE nickname IS NULL OR nickname IN (
            SELECT nickname
            FROM "user"
            GROUP BY nickname
            HAVING COUNT(*) > 1
        )
    """)
    op.alter_column('user', 'nickname', nullable=False)
    op.create_unique_constraint('uq_user_nickname', 'user', ['nickname'])
    op.drop_column('user', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', postgresql.ENUM('individual', 'organization', name='user_type'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_nickname', 'user', type_='unique')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'nickname')
    op.create_table('individual_profile',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('individual_profile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('individual_profile_pkey'))
    )
    op.create_table('provider',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('support_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('support_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('public_contact', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('provider_user_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('organization_profile',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('organization_profile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('organization_profile_pkey'))
    )
    op.drop_table('developer')
    # ### end Alembic commands ###
