"""update developer model

Revision ID: bccccb197bad
Revises: a46c3e048f48
Create Date: 2025-11-01 15:36:20.441452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccccb197bad'
down_revision: Union[str, Sequence[str], None] = 'a46c3e048f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer', sa.Column('github_profile', sa.String(length=255), nullable=True))
    op.drop_column('developer', 'public_contact')
    op.drop_column('developer', 'support_email')
    op.drop_column('developer', 'verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('developer', sa.Column('support_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('developer', sa.Column('public_contact', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('developer', 'github_profile')
    # ### end Alembic commands ###
