"""add agent_media table

Revision ID: 3b30c19b92a0
Revises: 815e65b9f7b1
Create Date: 2025-12-01 14:20:46.571675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b30c19b92a0'
down_revision: Union[str, Sequence[str], None] = '815e65b9f7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'versions', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'versions', type_='foreignkey')
    # ### end Alembic commands ###
