"""add long_description column to agents

Revision ID: ab6411fb435e
Revises: 476fe9209f3c
Create Date: 2025-12-18 08:31:24.004609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6411fb435e'
down_revision: Union[str, Sequence[str], None] = '476fe9209f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('long_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'long_description')
    # ### end Alembic commands ###
